# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-09 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortish', '0002_auto_20180208_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortishurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
