# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-15 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortish', '0003_auto_20180210_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortishurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
