# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-06 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import shortish.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortish', '0004_auto_20180215_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortishurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortish.validators.validate_url, shortish.validators.validate_dot_com]),
        ),
    ]
